### ISSUE TITLE
Uncalled function has 100% statement coverage of inner named functions

### ISSUE THREAD

**Issue by thetrevdev** [gotwarlost/istanbul#425]
```
function namedFn (){
  function a(){} //counted
  function b(){} //counted
  function c(){} //counted
  this.d = function(){} //not counted
}
```

```
=============================== Coverage summary ===============================
Statements   : 80% ( 4/5 )
Branches     : 100% ( 0/0 )
Functions    : 0% ( 0/5 )
Lines        : 80% ( 4/5 )
================================================================================
```

What am I missing?

**Comment by thetrevdev** [comment]
Looks like all function declarations are initialized to 1 and not instrumented.
https://github.com/gotwarlost/istanbul/blob/master/lib/instrumenter.js#L795
Couldn't all function declarations inside of a function scope be tracked and the first line of parent function be instrumented to increment all the function declarations at that time?

**Comment by thetrevdev** [comment]
Related to:
#417
Looks like this was to cover the case where the 'declaration' may be in an unreachable place and hoisted.  The fix to instrument the increments to the top seems like it would still work for declarations.

**Comment by gotwarlost** [comment]
This has a long and convoluted history. Basically function declarations and variable declarations w/o initializers should not be treated as statements by the coverage code and be excluded from coverage analysis. This needs to be fixed with a major version upgrade since it will change coverage reports for everyone.

I'm not making any patches on an already convoluted set of patches.

**Comment by thetrevdev** [comment]
Is there some open issue I can watch for changes?
