### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by skinnybrit51** [gotwarlost/istanbul#452]
This might sound stupid, but does Istanbul not report which files are not having any execution performed on them? It appears to me that Istanbul only reports on the files that have test files require them. Is this correct?

If it is correct, can you give any advice on tools that would produce a heat map of where testing exists and does not exist.

Thanks

**Comment by davglass** [comment]
Istanbul hooks into the `require` statement, so it can only cover files that have been `required` in your tests when they are executed. In the past I have written others scripts that gather my source tree and then compares those files against the JSON files that `istanbul` generated and got a listing of what wasn't covered. 

Since `istanbul` is only for covering files that execute it hard for it to guess what other things you expected to be covered that was not covered.

**Comment by skinnybrit51** [comment]
Can't istanbul use the src key array to determine the entire file directory. Then anytime a file is required it can mark it as being tested. Any files not marked would be noted as zero test coverage.

**Comment by gotwarlost** [comment]
```
$ istanbul help cover

...blah blah

      --include-all-sources
              instrument all unused sources after running tests, defaults to
              false

...blah blah
```
