### ISSUE TITLE
istanbul cover exits early

### ISSUE THREAD

**Issue by clux** [gotwarlost/istanbul#466]
Hi. I'm having a bit of a weird issue, where I am running a folder of tests through the fairly simple [tape binary](https://github.com/substack/tape/blob/master/bin/tape), but when running it through `istanbul cover tape -- test/*.js`, istanbul will often start printing the summary before all asserts are done, and there isn't even anything asynchronous in the tests - it's literally just one executable file requiring all my test files.

I've noticed that if I swap out the globbing mechanism in that file for just requiring all the files directly, istanbul cover works fine and never exits early. Is there something intended/weird here? Is `istanbul cover` doing something special with globs or aguments perhaps?

**Comment by gotwarlost** [comment]
No, `istanbul cover` does nothing special with globs or arguments. Note however that in your version of the command, `tape` does not literally see `test/*.js` - it probably sees the arguments after shell expansion. 

Try single-quoting the last argument and see if that helps. 

This is not to say I understand what might be going on but it might help you debug.

**Comment by clux** [comment]
Yeah, sorry. I have today managed to get it to fail with just plain requiring all the files, and now it actually failed once even without running it through istanbul. This is probably something race-y in `tape`.

**Comment by VPhantom** [comment]
For what it's worth, I had the same issue with a very small package I'm experimenting with, and I didn't need globbing to reproduce it: `istanbul cover test.js`

In order to preserve clean TAP output for `faucet` (and eventually Travis-CI I suppose), I had to forego the summary by using `istanbul cover --print none test.js`.  A shame though, because I really liked seeing the summary right there after the test results.
