### ISSUE TITLE
Failing to catch missing branch

### ISSUE THREAD

**Issue by isaacs** [gotwarlost/istanbul#526]
Hi, I found a case where istanbul seems to fail to notice that a branch isn't covered.

```javascript
function test (obj) {
  if (obj.a && !obj.b) {
    console.log('a and not b')
  }
}

test({
  a: true,
  b: false
})

test({
  a: false,
  b: false
})
```

The coverage report shows 100%, even though the "a and b" case is never called:

```
$ nyc node istanbul-issue-1.js
a and not b
----------------------|----------|----------|----------|----------|----------------|
File                  |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------------|----------|----------|----------|----------|----------------|
 __root__/            |      100 |      100 |      100 |      100 |                |
  istanbul-issue-1.js |      100 |      100 |      100 |      100 |                |
----------------------|----------|----------|----------|----------|----------------|
All files             |      100 |      100 |      100 |      100 |                |
----------------------|----------|----------|----------|----------|----------------|
```

If I split the conditional into two, it catches the missing branch:

```javascript
function test (obj) {
  if (obj.a) {
    if (!obj.b) {
      console.log('a and not b')
    }
  }
}

test({
  a: true,
  b: false
})

test({
  a: false,
  b: false
})
```

```
$ nyc node istanbul-issue-2.js
a and not b
----------------------|----------|----------|----------|----------|----------------|
File                  |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------------|----------|----------|----------|----------|----------------|
 __root__/            |      100 |       75 |      100 |      100 |                |
  istanbul-issue-2.js |      100 |       75 |      100 |      100 |                |
----------------------|----------|----------|----------|----------|----------------|
All files             |      100 |       75 |      100 |      100 |                |
----------------------|----------|----------|----------|----------|----------------|
```

EDIT: updated to remove the `condition()` function, which is not essential to the bug.

**Comment by gotwarlost** [comment]
This is a bug w.r.t to user expectations but istanbul is working as designed.

In the first case:

```
if (something) {
  console.log('something')
} 
```
your tests exercise both the if and else branch

In the second case:

```
if (something) {
  if (somethingelse) {
     console.log('something and something else')
  }
}
```

istanbul says that the else path of `somethingelse` was not exercised.

The problem is the istanbul does not peek into conditional expressions and "unravel" it into the second form. Doing this in a general purpose way is pretty hard and even if it is solvable displaying the branch results (w.r.t to the source code in the html report) in a way that the user can get what's going in is likely to be another not-easily-solvable issue.

There are many variations of the issue that you have raised and I haven't looked at solving this so far...

Ideas welcome.

**Comment by isaacs** [comment]
Yeah, I think what surprised me is that it seems to grok when you do something like:

```javascript
a = b || false
```

and b is always true.  But that isn't covered in if() conditionals.

In https://github.com/isaacs/node-lru-cache/pull/70, it led to appearance of 100% test coverage, where clearly there was a case being missed.

Could be that this is just a limit of what a mechanical coverage reporter can do, and an edge case that requires human brains?

**Comment by gotwarlost** [comment]
Although in a related example 

```
a = b || {};
```

The `b` part will show up as covered even when it is always false and the default is used. Which is basically the root cause of the issue you are seeing.

I think it might be possible to rewrite conditionals in a general way to get the effect you need. It's almost impossible IMO for a user to make sense of the coverage data when looking at source code annotations.

istanbul is used by a wide set of users with varying skill levels and the current version sacrifices strict correctness for usability and tries to get things "mostly right" :)

**Comment by isaacs** [comment]
Hm, I see what you're saying.  I'm happy to accept that this is just an edge case that automated JS code coverage can't provide.
