### ISSUE TITLE
Istanbul thinks } needs coverage

### ISSUE THREAD

**Issue by Gum-Joe** [gotwarlost/istanbul#590]
I was running my `mocha` tests, using istanbul, to create coverage to submit to coveralls. When I load up coveralls, I think I have 100% coverage of one of my files (`loader.js`). Coveralls says I do not, as a `}` and a `})` are not covered:
![image](https://cloud.githubusercontent.com/assets/12299307/14322012/4bf9b3a6-fc13-11e5-995c-cc812cdedf79.png)
Why is `istanbul` thinking that a `}` and a `})` need to be covered?
How can I stop it from thinking `}` and `})` need to be covered?
**NB:** In case it helps, `istanbul` says the code that matches up to the `}` and `})` are covered.
My code that is being tested, minus the module dependencies:
```javascript
/**
 * Load file
 *
 * @param file {String} File to load from
*/
app.loadFromFile = (file, callback) => {
  logger.debug('Loading from file...')
  fs.stat(path.join(PWD, file), function (err, stat) {
    if (err) {
      /* istanbul ignore next */
      logger.info('Could not find a \'buildupfile.js\' in the current directory!')
      logger.err(
        err,
        'the fact we couldn\'t find a \'buildupfile.js\' in the current directory',
        'To create a new file, run \'buildup init\''
      )
      if (callback) {
        callback(err);
      }
    }
  })
  logger.debug('Loading file...')
  let fileloaded = require(path.join(PWD, file))(api.api())
  return api.that;
}
```

**Comment by codekirei** [comment]
Do you have a test case for the implied `else` of `if (err)` in the callback function to `fs.stat` (i.e. when there is no error)? The location of the `}` and `})` that are showing as not covered make me think the `else` path is not being covered.

If that is the case, the fix is to write a case for the `else` path or use `/* istanbul ignore else */`.

**Comment by Gum-Joe** [comment]
Ok

**Comment by Gum-Joe** [comment]
I do have a test car for the if statement

**Comment by Gum-Joe** [comment]
@codekirei Just realised: my test checks for a 'module not found' error

**Comment by codekirei** [comment]
@Gum-Joe While it is true that you have no `else` statement, you *do* have an `if` statement, so by default there is a branch in your logic that can go one of two directions:

1. `if` clause is `true` -> run code inside `if` block
2. `if` clause is `false` -> do not run code inside `if` block (implied `else` case)

For 100% coverage, you need to test both of these cases. My suspicion is that your are only testing the first.

Some simple code to illustrate:
```js
// is-foo.js
function isFoo(str) {
  if (str === 'foo') {
    return true
  }
}
```
```js
// test.js (mocha style)
const assert = require('assert')
const isFoo = require('./is-foo')

describe('isFoo', () => {
  it('returns true if param === "foo"', () => {
    assert.equal(isFoo('foo'), true)
  })
  it('does not return true if param !== "foo"', () => {
    assert.notEqual(isFoo('bar'), true)
  })
})
```
`isFoo` has no `else`, but because it has an `if`, I still have to test for what happens when the `if` is `false`.

**Comment by codekirei** [comment]
Also, I just noticed that the code in your screenshot doesn't contain the following code while the code you posted does:

```js
if (callback) {
  callback(err);
}
```

Maybe that's part of the issue?

**Comment by Gum-Joe** [comment]
@codekirei Thanks for your advice! To solve the problem, I simply removed the callback code:
```javascript
if (callback) {
  callback(err);
}
```
This caused my coverage to go up to 50%
Happy coding!
